#include<iostream>
using namespace std;
int main()
{
	string movieName;
	int atp,ctp,na,nc,ta;
	float per,profit;
	cout<<"Enter movie name = ";
	cin>>movieName;
	cout<<"Enter adult ticket price = ";
	cin>>atp;
	cout<<"Enter child ticket price = ";
	cin>>ctp;
	cout<<"Enter number of adult tickets sold = ";
	cin>>na;
	cout<<"Enter number of child ticket sold = ";
	cin>>nc;
	cout<<"Enter percentage of the amount to be denote to the charity = ";
	cin>>per;
	ta = (atp*na)+(ctp*nc);
	per = (ta*per)/100.0;
	profit=ta-per;
	cout<<endl<<endl<<"_____________________________________________"<<endl<<endl<<endl;
	cout<<"The total amount generated by sold tickets = "<<ta;
	cout<<endl<<"profit amount after denoting = "<<profit<<endl<<endl;
	
	
	
	
	
	
}
